### DISCUSSION TITLE
11ty Image to Lume Imagick

### DISCUSSION THREAD

**Discussion by simplerethink** [lumeland/lume#350] [Q&A]
I'm considering migrating from 11ty to Lume.

In 11ty, image processing has the ability to create [custom file names](https://www.11ty.dev/docs/plugins/image/#custom-filenames) and [file hashes](https://www.11ty.dev/docs/plugins/image/#change-the-default-hash-length)

In 11ty, I can do something like this:
```
let metadata = await Image(src, {
        widths: [450, 550, 800],
        formats: ["webp", "jpeg", "avif"],
        outputDir: "./processed-img/",
        hashLength: 10,
        // Define custom filenames for generated images
        filenameFormat: function (id, src, width, format, options) {
            const extension = path.extname(src);
            const name = path.basename(src, extension);

            return `${name}-${width}w-${id}.${format}`;
        },
    });
```

This produces something like `mountain-450w-OsnQ_vZGAM.webp`

Is there similar capability in Lume? If not, could this be considered as a feature request?

**Comment by oscarotero** [comment]
Lume has the [imagick](https://lume.land/plugins/imagick/) plugin that can transform an image and outputs different versions. For example you can create a `_data.yml` in your images folder with the following data:

```yml
imagick:
  - resize: [450]
    format: [webp, jpeg, avif]
    suffix: -450
  - resize: [550]
    format: [webp, jpeg, avif]
    suffix: -550
  - resize: [800]
    format: [webp, jpeg, avif]
    suffix: -800
```

Or if you don't want to keep this configuration manually, you can create a  `_data.ts` file that generate this data for you:

```ts
const formats = ["webp", "jpeg", "avif"];
const sizes = [450, 550, 800];

export const imagick = sizes.map((size) => {
  return {
    resize: [size],
    formats,
    suffix: `-${size}`
  };
})
```
