### DISCUSSION TITLE
How use Multilanguage in jsx?

### DISCUSSION THREAD

**Discussion by cawa-93** [lumeland/lume#455] [Q&A] [answered]
How I can use [Language suffixes](https://lume.land/plugins/multilanguage/#language-suffixes) in jsx file?

**Comment by oscarotero** [comment, marked as answer]
I think it's not possible to export a variable with a dot in the name. This will fail

```js
export const title.en = "Title";
export const title.gl = "Título";
```

But you can export the [language variables](https://lume.land/plugins/multilanguage/#language-root-variables):

```js
export const en = {
  title: "Title",
}

export const gl = {
  title: "Título",
}
```

**Reply by cawa-93** [reply]
Yes, I use language variables. But I would like to export some array of objects in which only a few fields are subject to translation. As in this yaml demo
```yaml
links:
  - title: My personal site
    title.gl: O meu sitio persoal # The link title in galician
    title.es: Mi sitio personal # The link title in spanish
    url: https://oscarotero.com

  - title: Lume
    url: https://lume.land
```
