### DISCUSSION TITLE
Building a navigation / menu

### DISCUSSION THREAD

**Discussion by sagikazarmark** [lumeland/lume#718] [General]
I'm trying to replicate something similar to Hugo's menu feature.

I got started by writing a menu in shared data:

```yaml
menu:
  - title: Page
    url: /page
  - title: Foo
    url: https://domain.com
```

I'm having trouble figuring out the current page. I know I can hack around with the `url` variable, but that's kinda hacky.

I also tried using the search plugin, but I can't seem to find a way to search a page by a URL.

Are there any examples out there?

**Comment by sagikazarmark** [comment]
For the record:

I tried comparing URLs, but that's not 100% accurate solution (eg. trailing slashes can cause trouble).

**Comment by sagikazarmark** [comment]
Okay, here is the latest version:

```yaml
menu:
  - page: now
  - title: Slides
    url: https://slides.sagikazarmark.hu
```

```html
                {{- for entry of menu }}
                    {{- if entry.page }}
                        {{ set page = search.page("basename="+entry.page) }}

                        <a href="{{ page.url |> url(true) }}" class="text-gray-600 hover:text-gray-900 {{ if page.url == url }} font-semibold{{ else }} font-medium{{ /if }}" {{ if page.url == url }} aria-current="page"{{ /if }}>
                            {{ entry.title || page.title }}
                        </a>
                    {{ else }}
                        <a href="{{ entry.url }}" class="text-gray-600 hover:text-gray-900 font-medium">
                            {{ entry.title }}
                        </a>
                    {{ /if }}
                {{ /for }}

```

Basically, I can search pages based on basename and compare those URLs to the current URL.
