### ISSUE TITLE
Parcel Plugin should add a source-mapping comment

### ISSUE THREAD

**Issue by binyamin** [lumeland/lume#207]
when I run CSS through parcel, I expect the CSS file to reference the source-map using a source-mapping comment.
```css
body{color:red}
/* sourceMappingURL=style.css.map */
```
