### ISSUE TITLE
Metas plugin: allow relative urls for images

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#255]
So users can do the following:

```yml
metas
  title: "Hello world"
  description: "My first post"
  image: "./hello-world.png"
```
