### ISSUE TITLE
Imagick plugin: Allow `format` property to accept an array

### ISSUE THREAD

**Issue by paulrobertlloyd** [lumeland/lume#268]
Currently, `format` only allows a single value. If you want to output multiple formats, you need to declare separate transformations

```yml
imagick:
  - resize: [200, 200]
    suffix: -small
    format: jpg
  - resize: [200, 200]
    suffix: -small
    format: webp
```

To simplify the configuration of different image transformations, it would be helpful if the `format` property could accept an array. This would allow the above to be rewritten as follows:

```yml
imagick:
  - resize: [200, 200]
    suffix: -small
    format:
      - jpg
      - webp
```
