### ISSUE TITLE
Lightening CSS plugin: Can’t use custom media values in components

### ISSUE THREAD

**Issue by paulrobertlloyd** [lumeland/lume#273]
Custom media properties, if enabled, are parsed by Lighting CSS in any processed stylesheets. For example:

```css
/* src/app.css */

@custom-media --from-small-viewport (width >= 640px);

body {
  background-color: red;
}

@media (--from-small-viewport) {
  body {
    background-color: blue;
  }
}
```

is translated to:

```css
/* _site/app.css */

body {
  background-color: red;
}

@media (min-width: 640px) {
  body {
    background-color: blue;
  }
}
```

However, if I use this custom media value in a component, I get the following error: `Custom media query --from-small-viewport is not defined`.

I suspect this might be related to https://github.com/parcel-bundler/lightningcss/issues/277, so somewhat expected behaviour for now, but thought it was worth recording as an issue, as this behaviour initially confused me.
