### ISSUE TITLE
Use property alias for `metas` plugin

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#321]
### Enter your suggestions in details:

The `metas` plugin has the `defaultPageData` option to configure default values for the `metas` properties. I think this is not convenient due two reasons:

- It cannot be configured per page because it's defined in the `_config.ts` file
- If some defaults values are defined in a `_data` file (for example, `metas.title`), then you need to do `metas.title = null` to use the default value configured.

I propose to change the plugin to implement a syntax to define aliases to existing variables. For example:

```yml
title: Hello world
description: This is my site

metas:
  title: $title
  description: $description
```

Any value starting with `$` sign would be interpreted as an alias to an existing value (in the example above, `title` and `description`. It could allow also values like `$header.title`.

This allows to have different defaults for different types of pages, using `_data` files in subfolders.

**Edit:**

Maybe the sign `~` is better, because it's what's used by the `url` plugin to refer to source files (like `~/about-me.md`):

```yml
title: Hello world
description: This is my site

metas:
  title: ~title
  description: ~description
```

Other alternative syntaxes:

```yml
title: Hello world
description: This is my site

metas:
  title: &title
  description: &description
```
(Cons: The `&` sign is a thing in Yaml).

```yml
title: Hello world
description: This is my site

metas:
  title: {{ title }}
  description: {{ description }}
```
(Const: It looks like nunjucks, people may think it's possible to use filters and other nunjucks features).

Any feedback is welcome!
