### ISSUE TITLE
Github Actions error: pagefind: 1: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by ehaughee** [lumeland/lume#438]
### Version

1.17.5

### Platform

ubuntu-latest

### What steps will reproduce the bug?

Created a Lume project with the simple blog plugin.

`_config.ts`
```typescript
import lume from "lume/mod.ts";
import blog from "https://deno.land/x/lume_theme_simple_blog@v0.5.0/mod.ts";

const site = lume();

site.use(blog());

export default site;
```

Followed the [Deployment](https://lume.land/docs/advanced/deployment/) docs and created a deno project, the `deno.yml`, and a `serve.ts`.

`deno.yml`
```yml
name: Publish on Deno Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: <my deno project name>
          import-map: "./import_map.json"
          entrypoint: serve.ts

```

`serve.ts`
```typescript
import Server from "lume/core/server.ts";

const server = new Server({
  port: 8000,
  root: `${Deno.cwd()}/_site`,
});

server.start();

console.log("Listening on http://localhost:8000");
```

Enabled actions on my Github repository after pushing.  Action ran and failed with the error:
```

Using binary file at /home/runner/work/what-it-b-log/what-it-b-log/_bin/pagefind

Error: Pagefind exited with code 2



/home/runner/work/what-it-b-log/what-it-b-log/_bin/pagefind: 1: Syntax error: word unexpected (expecting ")")

    at (https://deno.land/x/lume@v1.17.5/plugins/pagefind.ts:192:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Events.dispatchEvent (https://deno.land/x/lume@v1.17.5/core/events.ts:49:11)
    at async Site.build (https://deno.land/x/lume@v1.17.5/core/site.ts:538:5)
    at async build (https://deno.land/x/lume@v1.17.5/cli/build.ts:41:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.17.5/cli.ts:134:3)
Error: Process completed with exit code 1.
```

### How often does it reproduce? Is there a required condition?

Every retry of the build fails in the exact same way.

### What is the expected behavior?

Deployment succeeds.

### What do you see instead?

Deployment failure with above mentioned error.
