### ISSUE TITLE
HighlightJS plugin does not honor position with css placeholders

### ISSUE THREAD

**Issue by RickCogley** [lumeland/lume#745]
### Version

f57483a1d5db94ba956525471b96155cda5810fa

### Platform

macOS

### What steps will reproduce the bug?

Setup highlightjs plugin, add placeholders to css in specific positions, see generated css, which just has the highlightjs css at the bottom of the file. 

### How often does it reproduce? Is there a required condition?

Consistently

### What is the expected behavior?

I'd like to be able to specify the position of light and dark mode. 

Given: 

```ts
site.use(codeHighlight(
  {
    theme: [
      {
        name: "atom-one-light",
        cssFile: "styles.css",
        placeholder: "/* light-theme-here */"
      },
      {
        name: "atom-one-dark",
        cssFile: "styles.css",
        placeholder: "/* dark-theme-here */"
      },
    ],
    languages: {
      bash: lang_bash,
      css: lang_css,
      html: lang_html,
      json: lang_javascript_json,
      javascript: lang_javascript,
      typescript: lang_javascript_ts,
      js: lang_javascript,
      ts: lang_javascript_ts,
      powershell: lang_powershell,
      shell: lang_shell,
      sql: lang_sql,
      yaml: lang_yaml,
    },
  },
));
```

And in my styles.css:

```css
:root {
  ::selection {
    background-color: var(--color-sky-300);
    color: var(--color-zinc-900); 
  }
  
/* light-theme-here */

  .dark {
    ::selection {
      background-color: var(--color-sky-300);
      color: var(--color-zinc-900);
    }

/* dark-theme-here */

  }
}
```

If possible I would like the classes to be merged in position I specify, so they are picked up with the correct mode.

### What do you see instead?

The css classes are merged in, at the bottom of the styles.css file:

```css
...
hljs{padding:3px 5px}.hljs{color:#383a42;background:#fafafa}.hljs-comment,.hljs-quote{color:#a0a1a7;font-style:italic}.hljs-doctag,.hljs-formula,.hljs-keyword{color:#a626a4}.hljs-deletion,.hljs-name,.hljs-section,.hljs-selector-tag,.hljs-subst{color:#e45649}.hljs-literal{color:#0184bb}.hljs-addition,.hljs-attribute,.hljs-meta .hljs-string,.hljs-regexp,.hljs-string{color:#50a14f}.hljs-attr,.hljs-number,.hljs-selector-attr,.hljs-selector-class,.hljs-selector-pseudo,.hljs-template-variable,.hljs-type,.hljs-variable{color:#986801}.hljs-bullet,.hljs-link,.hljs-meta,.hljs-selector-id,.hljs-symbol,.hljs-title{color:#4078f2}.hljs-built_in,.hljs-class .hljs-title,.hljs-title.class_{color:#c18401}.hljs-emphasis{font-style:italic}.hljs-strong{font-weight:700}.hljs-link{text-decoration:underline}
pre code.hljs{display:block;overflow-x:auto;padding:1em}code.hljs{padding:3px 5px}.hljs{color:#abb2bf;background:#282c34}.hljs-comment,.hljs-quote{color:#5c6370;font-style:italic}.hljs-doctag,.hljs-formula,.hljs-keyword{color:#c678dd}.hljs-deletion,.hljs-name,.hljs-section,.hljs-selector-tag,.hljs-subst{color:#e06c75}.hljs-literal{color:#56b6c2}.hljs-addition,.hljs-attribute,.hljs-meta .hljs-string,.hljs-regexp,.hljs-string{color:#98c379}.hljs-attr,.hljs-number,.hljs-selector-attr,.hljs-selector-class,.hljs-selector-pseudo,.hljs-template-variable,.hljs-type,.hljs-variable{color:#d19a66}.hljs-bullet,.hljs-link,.hljs-meta,.hljs-selector-id,.hljs-symbol,.hljs-title{color:#61aeee}.hljs-built_in,.hljs-class .hljs-title,.hljs-title.class_{color:#e6c07b}.hljs-emphasis{font-style:italic}.hljs-strong{font-weight:700}.hljs-link{text-decoration:underline}
EOF
```

The dark mode happened to be second, so it takes precedence, and even in light mode, the dark mode is displayed on the generated page.
